export const lifecycleEvents = [
  "assessment_created",
  "document_uploaded",
  "documents_ingested",
  "scf_pre_analysis_completed",
  "framework_selected",
  "scope_drafted",
  "soa_drafted",
  "soa_submitted_for_review",
  "soa_approved",
  "soa_ingested",
  "evidence_analysis_completed",
  "gap_analysis_drafted",
  "gap_analysis_submitted_for_review",
  "gap_analysis_approved",
  "maturity_assessed",
  "maturity_submitted_for_review",
  "maturity_approved",
  "poam_drafted",
  "poam_submitted_for_review",
  "poam_approved",
  "report_generated",
  "report_approved",
  "assessment_closed",
  "assessment_cancelled",
  "assessment_failed",
  "assessment_blocked"
] as const;

export type AssessmentLifecycleEventType = (typeof lifecycleEvents)[number];
