import type { FileSecurityPolicy, Permission, Role } from "@standard/schemas";

export const ALL_PERMISSIONS = [
  "tenant:read",
  "tenant:update",
  "organization:create",
  "organization:read",
  "organization:update",
  "organization:delete",
  "membership:manage",
  "assessment:create",
  "assessment:read",
  "assessment:update",
  "assessment:delete",
  "assessment:run_workflow",
  "assessment:close",
  "assessment:cancel",
  "document:upload",
  "document:read",
  "document:delete",
  "document:reprocess",
  "document:write",
  "kb:index",
  "kb:search",
  "kb:read",
  "kb:write",
  "scf:read",
  "scf:import",
  "scf:admin",
  "scf:create",
  "scope:create",
  "scope:update",
  "scope:approve",
  "soa:create",
  "soa:update",
  "soa:submit_review",
  "soa:approve",
  "soa:read",
  "evidence:run",
  "evidence:read",
  "gap:create",
  "gap:update",
  "gap:submit_review",
  "gap:approve",
  "gap:read",
  "maturity:create",
  "maturity:update",
  "maturity:submit_review",
  "maturity:approve",
  "maturity:read",
  "poam:create",
  "poam:update",
  "poam:submit_review",
  "poam:approve",
  "poam:read",
  "report:create",
  "report:render",
  "report:approve",
  "report:read",
  "report:download",
  "report:update",
  "agent:run",
  "agent:dry_run",
  "agent:read_runs",
  "agent:read",
  "agent:create",
  "agent:admin",
  "admin:read",
  "admin:write",
  "admin:create",
  "admin:delete",
  "admin:approve",
  "audit:read",
  "webhook:create",
  "webhook:read",
  "webhook:update",
  "webhook:delete",
  "artifact:create",
  "artifact:read",
  "artifact:update",
  "artifact:approve",
  "approval:create",
  "approval:read",
  "privacy:create",
  "privacy:read",
  "privacy:update",
  "privacy:delete",
  "intelligence:read",
  "intelligence:create",
] as const satisfies readonly Permission[];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  platform_admin: [...ALL_PERMISSIONS],
  customer: [
    // Organization
    "organization:create",
    "organization:read",
    "organization:update",
    "organization:delete",
    "membership:manage",
    // Assessment lifecycle
    "assessment:create",
    "assessment:read",
    "assessment:update",
    "assessment:delete",
    "assessment:run_workflow",
    "assessment:close",
    "assessment:cancel",
    // Documents
    "document:upload",
    "document:read",
    "document:delete",
    "document:reprocess",
    "document:write",
    // KB
    "kb:index",
    "kb:search",
    "kb:read",
    "kb:write",
    // SCF (read-only)
    "scf:read",
    // Scope & SoA
    "scope:create",
    "scope:update",
    "scope:approve",
    "soa:create",
    "soa:update",
    "soa:submit_review",
    "soa:approve",
    "soa:read",
    // Evidence
    "evidence:run",
    "evidence:read",
    // Gap Analysis
    "gap:create",
    "gap:update",
    "gap:submit_review",
    "gap:approve",
    "gap:read",
    // Maturity
    "maturity:create",
    "maturity:update",
    "maturity:submit_review",
    "maturity:approve",
    "maturity:read",
    // POA&M
    "poam:create",
    "poam:update",
    "poam:submit_review",
    "poam:approve",
    "poam:read",
    // Reporting
    "report:create",
    "report:render",
    "report:approve",
    "report:read",
    "report:download",
    "report:update",
    // Agents
    "agent:run",
    "agent:dry_run",
    "agent:read_runs",
    "agent:read",
    "agent:create",
    // Webhooks
    "webhook:create",
    "webhook:read",
    "webhook:update",
    "webhook:delete",
    // Artifacts
    "artifact:create",
    "artifact:read",
    "artifact:update",
    "artifact:approve",
    // Approvals
    "approval:create",
    "approval:read",
    // Privacy
    "privacy:create",
    "privacy:read",
    "privacy:update",
    "privacy:delete",
    // Intelligence
    "intelligence:read",
    "intelligence:create",
    // Audit
    "audit:read",
    // Tenant (own org usage/stats)
    "tenant:read",
  ],
  system: [
    "assessment:read",
    "assessment:update",
    "assessment:run_workflow",
    "kb:index",
    "agent:run",
    "agent:read_runs",
    "report:render",
  ],
};

export const DEFAULT_FILE_SECURITY_POLICY: FileSecurityPolicy = {
  max_file_size_bytes: 10 * 1024 * 1024,
  allowed_extensions: ["pdf", "docx", "txt", "md", "markdown", "csv", "json"],
  allowed_mime_types: [
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/csv",
    "application/json",
    "text/json",
  ],
  require_content_hash: true,
  require_malware_scan: true,
  quarantine_on_rejection: true,
};
