import type { FileSecurityPolicy, Permission, Role } from "@standard/schemas";

export const ALL_PERMISSIONS = [
  "tenant:read",
  "tenant:update",
  "organization:create",
  "organization:read",
  "organization:update",
  "membership:manage",
  "assessment:create",
  "assessment:read",
  "assessment:update",
  "assessment:delete",
  "assessment:run_workflow",
  "assessment:close",
  "assessment:cancel",
  "document:upload",
  "document:read",
  "document:delete",
  "document:reprocess",
  "document:write",
  "kb:index",
  "kb:search",
  "kb:read",
  "kb:write",
  "scf:read",
  "scf:import",
  "scf:admin",
  "scf:create",
  "scope:create",
  "scope:update",
  "scope:approve",
  "soa:create",
  "soa:update",
  "soa:submit_review",
  "soa:approve",
  "soa:read",
  "evidence:run",
  "evidence:read",
  "gap:create",
  "gap:update",
  "gap:submit_review",
  "gap:approve",
  "gap:read",
  "maturity:create",
  "maturity:update",
  "maturity:submit_review",
  "maturity:approve",
  "maturity:read",
  "poam:create",
  "poam:update",
  "poam:submit_review",
  "poam:approve",
  "poam:read",
  "report:create",
  "report:render",
  "report:approve",
  "report:read",
  "report:download",
  "report:update",
  "agent:run",
  "agent:dry_run",
  "agent:read_runs",
  "agent:read",
  "agent:create",
  "agent:admin",
  "admin:read",
  "admin:write",
  "admin:create",
  "admin:delete",
  "admin:approve",
  "audit:read",
  "webhook:create",
  "webhook:read",
  "webhook:update",
  "webhook:delete",
  "artifact:create",
  "artifact:read",
  "artifact:update",
  "artifact:approve",
  "approval:create",
  "approval:read",
  "privacy:create",
  "privacy:read",
  "privacy:update",
  "privacy:delete",
  "intelligence:read",
  "intelligence:create",
] as const satisfies readonly Permission[];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  platform_admin: [...ALL_PERMISSIONS],
  tenant_admin: [
    "tenant:read",
    "tenant:update",
    "organization:create",
    "organization:read",
    "organization:update",
    "membership:manage",
    "assessment:create",
    "assessment:read",
    "assessment:update",
    "audit:read",
  ],
  organization_admin: [
    "organization:read",
    "organization:update",
    "assessment:create",
    "assessment:read",
    "assessment:update",
    "document:upload",
    "document:read",
    "kb:index",
    "kb:search",
    "soa:read",
    "gap:read",
    "poam:read",
    "report:read",
  ],
  assessment_owner: [
    "assessment:read",
    "assessment:update",
    "assessment:run_workflow",
    "assessment:cancel",
    "document:upload",
    "document:read",
    "document:reprocess",
    "kb:index",
    "kb:search",
    "scope:create",
    "scope:update",
    "soa:create",
    "soa:update",
    "soa:submit_review",
    "soa:read",
    "evidence:run",
    "evidence:read",
    "gap:create",
    "gap:update",
    "gap:submit_review",
    "gap:read",
    "maturity:create",
    "maturity:update",
    "maturity:submit_review",
    "maturity:read",
    "poam:create",
    "poam:update",
    "poam:submit_review",
    "poam:read",
    "report:create",
    "report:render",
    "report:read",
    "report:download",
    "agent:run",
    "agent:read_runs",
  ],
  assessor: [
    "assessment:read",
    "document:upload",
    "document:read",
    "document:reprocess",
    "kb:index",
    "kb:search",
    "scope:create",
    "scope:update",
    "soa:create",
    "soa:update",
    "soa:submit_review",
    "soa:read",
    "evidence:run",
    "evidence:read",
    "gap:create",
    "gap:update",
    "gap:submit_review",
    "gap:read",
    "poam:create",
    "poam:update",
    "poam:submit_review",
    "poam:read",
    "report:create",
    "report:render",
    "report:read",
    "agent:run",
    "agent:read_runs",
  ],
  reviewer: [
    "assessment:read",
    "document:read",
    "kb:search",
    "soa:read",
    "gap:read",
    "maturity:read",
    "poam:read",
    "report:read",
  ],
  approver: [
    "assessment:read",
    "document:read",
    "kb:search",
    "soa:read",
    "soa:approve",
    "gap:read",
    "gap:approve",
    "maturity:read",
    "maturity:approve",
    "poam:read",
    "poam:approve",
    "report:read",
    "report:approve",
    "report:download",
  ],
  auditor_readonly: [
    "assessment:read",
    "soa:read",
    "gap:read",
    "maturity:read",
    "poam:read",
    "report:read",
    "report:download",
    "audit:read",
  ],
  integration_service: [
    "assessment:read",
    "document:upload",
    "document:read",
    "kb:index",
    "kb:search",
    "report:read",
  ],
  support_readonly: [
    "tenant:read",
    "organization:read",
    "assessment:read",
    "audit:read",
  ],
  system: [
    "assessment:read",
    "assessment:update",
    "assessment:run_workflow",
    "kb:index",
    "agent:run",
    "agent:read_runs",
    "report:render",
  ],
};

/**
 * Maps Better Auth organization roles (from memberships table) to Standard GRC roles.
 *
 * Better Auth's organization plugin uses simple roles (owner, admin, member).
 * Standard's GRC RBAC uses domain-specific roles (organization_admin, assessment_owner, etc.).
 * This mapping bridges the two systems so session users get appropriate permissions.
 *
 * Future: Per-assessment role assignments will allow finer-grained roles
 * (approver, reviewer, auditor_readonly) without changing this base mapping.
 */
export const ORG_ROLE_TO_GRC_ROLE: Record<string, Role> = {
  owner: "organization_admin",
  admin: "assessment_owner",
  member: "assessor",
};

/**
 * Resolves a Better Auth org role to a Standard GRC role.
 * Returns null if the org role is unknown (defensive — should never happen).
 */
export const resolveGrcRoleFromOrgRole = (orgRole: string): Role | null => {
  return ORG_ROLE_TO_GRC_ROLE[orgRole] ?? null;
};

export const DEFAULT_FILE_SECURITY_POLICY: FileSecurityPolicy = {
  max_file_size_bytes: 10 * 1024 * 1024,
  allowed_extensions: ["pdf", "docx", "txt", "md", "markdown", "csv", "json"],
  allowed_mime_types: [
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/csv",
    "application/json",
    "text/json",
  ],
  require_content_hash: true,
  require_malware_scan: true,
  quarantine_on_rejection: true,
};
