import type { FileSecurityPolicy, Permission, Role } from "@standard/schemas";

export const ALL_PERMISSIONS = [
  "tenant:read",
  "tenant:update",
  "organization:create",
  "organization:read",
  "organization:update",
  "organization:delete",
  "membership:manage",
  "apikey:read",
  "apikey:manage",
  "assessment:create",
  "assessment:read",
  "assessment:update",
  "assessment:delete",
  "assessment:run_workflow",
  "assessment:close",
  "assessment:cancel",
  "document:upload",
  "document:read",
  "document:delete",
  "document:reprocess",
  "document:write",
  "kb:index",
  "kb:search",
  "kb:read",
  "kb:write",
  "scf:read",
  "scf:import",
  "scf:admin",
  "scf:create",
  "scope:create",
  "scope:update",
  "scope:approve",
  "soa:create",
  "soa:update",
  "soa:submit_review",
  "soa:approve",
  "soa:read",
  "evidence:run",
  "evidence:read",
  "gap:create",
  "gap:update",
  "gap:submit_review",
  "gap:approve",
  "gap:read",
  "maturity:create",
  "maturity:update",
  "maturity:submit_review",
  "maturity:approve",
  "maturity:read",
  "poam:create",
  "poam:update",
  "poam:submit_review",
  "poam:approve",
  "poam:read",
  "report:create",
  "report:render",
  "report:approve",
  "report:read",
  "report:download",
  "report:update",
  "agent:run",
  "agent:dry_run",
  "agent:read_runs",
  "agent:read",
  "agent:create",
  "agent:admin",
  "admin:read",
  "admin:write",
  "admin:create",
  "admin:delete",
  "admin:approve",
  "audit:read",
  "webhook:create",
  "webhook:read",
  "webhook:update",
  "webhook:delete",
  "artifact:create",
  "artifact:read",
  "artifact:update",
  "artifact:approve",
  "approval:create",
  "approval:read",
  "privacy:create",
  "privacy:read",
  "privacy:update",
  "privacy:delete",
  "intelligence:read",
  "intelligence:create",
] as const satisfies readonly Permission[];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  platform_admin: [...ALL_PERMISSIONS],
  // org_admin — the organization administrator. Sole human attribution is
  // managing the org's API keys (plus reading its own org context). All GRC
  // work (assessments, gap, poam, reports, …) runs via those API keys / M2M
  // scopes, NOT via this human role — so those permissions are intentionally
  // absent here and any GRC route will 403 for a bare org_admin session.
  org_admin: [
    "organization:read",
    "apikey:read",
    "apikey:manage",
    // Own-org usage/stats
    "tenant:read",
  ],
  system: [
    "assessment:read",
    "assessment:update",
    "assessment:run_workflow",
    "kb:index",
    "agent:run",
    "agent:read_runs",
    "report:render",
  ],
};

export const DEFAULT_FILE_SECURITY_POLICY: FileSecurityPolicy = {
  max_file_size_bytes: 10 * 1024 * 1024,
  allowed_extensions: ["pdf", "docx", "txt", "md", "markdown", "csv", "json"],
  allowed_mime_types: [
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/csv",
    "application/json",
    "text/json",
  ],
  require_content_hash: true,
  require_malware_scan: true,
  quarantine_on_rejection: true,
};
