import { extendZodWithOpenApi, OpenAPIRegistry, OpenApiGeneratorV3 } from "@asteasolutions/zod-to-openapi";
import { z } from "zod";

// Initialize extensions on zod
extendZodWithOpenApi(z);

export const registry = new OpenAPIRegistry();

// ==========================================
// Security Schemes
// ==========================================

registry.registerComponent("securitySchemes", "BearerApiKey", {
  type: "http",
  scheme: "bearer",
  description: "API Key issued from the Standard dashboard. Prefix: `standard_live_` or `standard_test_`."
});

registry.registerComponent("securitySchemes", "CookieSession", {
  type: "apiKey",
  in: "cookie",
  name: "better-auth.session_token",
  description: "Session cookie set by Better Auth after login."
});

// ==========================================
// Shared Error Schema
// ==========================================

const ApiErrorSchema = z.object({
  error: z.object({
    code: z.string().openapi({ example: "NOT_FOUND" }),
    message: z.string().openapi({ example: "Assessment not found." }),
    details: z.array(z.unknown()).optional(),
    trace_id: z.string().openapi({ example: "abc-123-def" })
  })
}).openapi("ApiError");

const PaginatedMeta = z.object({
  page: z.number(),
  per_page: z.number(),
  total: z.number()
}).openapi("PaginatedMeta");

// ==========================================
// Zod Schemas Instrumentation (Agentic Privacy)
// ==========================================

export const RopaAnalysisOutputSchema = z.object({
  suggested_risk_level: z.enum(["low", "medium", "high", "critical"])
    .openapi({ description: "Primary risk level deduced from the data processing activity." }),
  required_controls: z.array(z.object({
    control_id: z.string(),
    name: z.string(),
    reason: z.string()
  })).openapi({ description: "List of suggested controls via SCF." }),
  suggested_legal_basis: z.string().openapi({ description: "Deduced LGPD/GDPR legal basis." }),
  is_dpia_required: z.boolean().openapi({ description: "Whether a DPIA should be triggered in the agentic chain." })
}).openapi("RopaAnalysisOutput");

export const DpiaAssessmentInputSchema = z.object({
  projectDescription: z.string().min(5).openapi({ example: "Project integrating the accounting API" }),
  ropaContext: RopaAnalysisOutputSchema
}).openapi("DpiaAssessmentInput");

export const EvidenceEvaluationInputSchema = z.object({
  controlRequirement: z.string().min(10).openapi({ example: "Backup data must be stored at rest with AES-256 encryption." }),
  evidenceDescription: z.string().openapi({ example: "Our AWS buckets use the native SSE-S3 flag." })
}).openapi("EvidenceEvaluationInput");

export const EvidenceEvaluationOutputSchema = z.object({
  is_compliant: z.boolean().openapi({ description: "Whether the evidence successfully covers the requirement." }),
  confidence_score: z.number().min(0).max(100).openapi({ description: "Confidence score of adequacy (0-100)." }),
  missing_elements: z.array(z.string()).openapi({ description: "Technical elements missing if the control fails evaluation." }),
  auditor_notes: z.string().openapi({ description: "Technical assessment generated by the LLM Auditor." })
}).openapi("EvidenceEvaluationOutput");

export const PoamRemediationInputSchema = z.object({
  evidenceContext: EvidenceEvaluationOutputSchema,
  systemArchitectureDescription: z.string().openapi({ example: "AWS ECS containerized with internal network." })
}).openapi("PoamRemediationInput");

export const PoamRemediationOutputSchema = z.object({
  priority_level: z.string().openapi({ description: "Architectural severity of the failure." }),
  estimated_effort: z.string().openapi({ description: "DevOps task size (small/medium/large)." }),
  sprint_action_items: z.array(z.string()).openapi({ description: "Epic broken into sub-tasks." }),
  devops_commands_suggested: z.array(z.string()).openapi({ description: "Recommended scripts to apply the fix." })
}).openapi("PoamRemediationOutput");

export const VendorScannerInputSchema = z.object({
  vendorName: z.string().openapi({ example: "Amazon Web Services (AWS)" }),
  contractExcerpt: z.string().min(20).openapi({ example: "5.1 The Processor agrees to notify the Controller of any breach within 120 hours." })
}).openapi("VendorScannerInput");

export const VendorScannerOutputSchema = z.object({
  has_standard_contractual_clauses: z.boolean().openapi({ description: "Whether the contract has EU/ANPD standardized DPA clauses." }),
  is_dpa_compliant: z.boolean().openapi({ description: "Whether the contract is globally compliant for LGPD/GDPR." }),
  liability_cap_identified: z.string().optional().openapi({ description: "Liability cap paid by the vendor." }),
  data_subprocessors_listed: z.array(z.string()).openapi({ description: "Third-party companies detected in the contract text." }),
  red_flags_for_negotiation: z.array(z.string()).openapi({ description: "Severe gaps that the legal team needs to renegotiate." })
}).openapi("VendorScannerOutput");

export const IncidentTriagerInputSchema = z.object({
  systemModuleName: z.string().openapi({ example: "WAF Edge Firewall" }),
  rawLogsExcerpt: z.string().min(10).openapi({ example: "[10/Oct/2026:13:55:36 +0000] 'GET /admin' 403 154 '-' 'SqlMap/1.4'" })
}).openapi("IncidentTriagerInput");

export const IncidentTriagerOutputSchema = z.object({
  is_false_positive: z.boolean().openapi({ description: "Identifica se é apenas ruído ou tráfego lícito." }),
  severity_level: z.enum(["low", "medium", "high", "critical"]).openapi({ description: "Gravidade real calculada pelo Agente L3." }),
  attack_vector_guessed: z.string().openapi({ description: "Vetor provável (ex: SQL Injection)." }),
  affected_assets_identified: z.array(z.string()).openapi({ description: "Hosts ou módulos sob ataque." }),
  immediate_containment_actions: z.array(z.string()).openapi({ description: "Playbook rápido de contenção." }),
  requires_dpo_breach_notification: z.boolean().openapi({ description: "Se PII estiver exposto, deve disparar a notificação oficial DPO LGPD." })
}).openapi("IncidentTriagerOutput");

export const BoardTranslatorInputSchema = z.object({
  technicalRiskDescription: z.string().min(10).openapi({ example: "Vulnerabilidade no pod kube-system expondo porta 10250 sem auth (CVE-2018-1002105)." }),
  riskCategory: z.enum(["security", "privacy", "compliance", "architecture"]).openapi({ example: "security" }),
  businessContext: z.string().optional().openapi({ example: "Cluster roda os pagamentos de Black Friday." })
}).openapi("BoardTranslatorInput");

export const BoardTranslatorOutputSchema = z.object({
  executive_summary: z.string().openapi({ description: "Plain-language summary without excessive jargon." }),
  financial_impact_estimate: z.string().openapi({ description: "Descriptive estimate of financial loss if the risk materializes." }),
  regulatory_impact: z.string().openapi({ description: "Fines or legal requirements involved." }),
  board_level_recommendation: z.string().openapi({ description: "What the board should approve (e.g., buy WAF, allocate budget)." }),
  urgency_metric: z.number().min(0).max(100).openapi({ description: "Board urgency score (0-100)." })
}).openapi("BoardTranslatorOutput");

// ==========================================
// Agent Runtime Schemas
// ==========================================

const AgentRunSchema = z.object({
  agent_run_id: z.string().openapi({ example: "run_abc123" }),
  agent_id: z.string().openapi({ example: "evidence-evaluator" }),
  agent_version: z.string().openapi({ example: "1.0.0" }),
  model: z.string().openapi({ example: "gpt-4o" }),
  status: z.string().openapi({ example: "running" }),
  tenant_id: z.string(),
  assessment_id: z.string(),
  created_at: z.string()
}).openapi("AgentRun");

const StartAgentRunInput = z.object({
  agent_id: z.string().openapi({ example: "evidence-evaluator" }),
  agent_version: z.string().openapi({ example: "1.0.0" }),
  prompt_version: z.string().openapi({ example: "1.0.0" }),
  model: z.string().openapi({ example: "gpt-4o" }),
  framework_id: z.string().openapi({ example: "ISO27001" }),
  scf_version_id: z.string().openapi({ example: "2026.1.1" }),
  input: z.record(z.string(), z.unknown()).openapi({ example: { controlRequirement: "AES-256 encryption at rest", evidenceDescription: "S3 SSE-S3 enabled" } })
}).openapi("StartAgentRunInput");

// ==========================================
// Assessment Schemas
// ==========================================

const AssessmentSchema = z.object({
  assessment_id: z.string(),
  name: z.string(),
  state: z.string().openapi({ example: "draft" }),
  framework_id: z.string().optional(),
  tenant_id: z.string(),
  organization_id: z.string(),
  created_at: z.string(),
  updated_at: z.string()
}).openapi("Assessment");

const CreateAssessmentInput = z.object({
  name: z.string().min(1).openapi({ example: "ISO 27001 Assessment Q2 2026" }),
  description: z.string().optional().openapi({ example: "Annual security assessment" })
}).openapi("CreateAssessmentInput");

// ==========================================
// Intelligence Engine Schemas
// ==========================================

import {
  GapAnalysisRequestSchema,
  ComplianceScoreRequestSchema,
  DpiaScoreRequestSchema,
  CrossCoverageRequestSchema,
  RoiPathRequestSchema,
  BlastRadiusRequestSchema,
  BlastRadiusOutputSchema,
  GapAnalysisOutputSchema,
  ComplianceScoreOutputSchema,
  DpiaScoreOutputSchema,
  CrossCoverageOutputSchema,
  RoiPathOutputSchema
} from "./schemas/intelligence.schema";// ==========================================
// Health Schema
// ==========================================

const HealthResponseSchema = z.object({
  status: z.string().openapi({ example: "ok" }),
  version: z.string().openapi({ example: "1.0.0" }),
  uptime_ms: z.number(),
  counters: z.object({
    total_requests: z.number(),
    total_errors: z.number(),
    avg_latency_ms: z.number()
  }).optional()
}).openapi("HealthResponse");

// ==========================================
// Definitions Documentation
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/privacy/analyze-ropa",
  summary: "Analyze Data Processing Activities (RoPA Agent)",
  description: "Given a natural-language description from the user, the AI deduces applicable controls, risk level, and legal basis (Structured Output).",
  request: {
    body: {
      content: {
        "application/json": {
          schema: z.object({
            text: z.string().openapi({ example: "We digitize medical data from clients at the reception desk." })
          })
        }
      }
    }
  },
  responses: {
    200: {
      description: "Agentic analysis result",
      content: { "application/json": { schema: RopaAnalysisOutputSchema } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/privacy/assess-dpia",
  summary: "DPIA Triage (Agentic Chaining)",
  description: "Requires a previously generated RoPA output as input, producing a deep residual risk assessment with conditional technical approval.",
  request: {
    body: {
      content: {
        "application/json": {
          schema: DpiaAssessmentInputSchema
        }
      }
    }
  },
  responses: {
    200: {
      description: "DPIA assessment result",
      content: { 
        "application/json": { 
          schema: z.object({
            residual_risk_level: z.string(),
            is_approved_technically: z.boolean(),
            mitigating_controls_required: z.array(z.string()),
            is_draft: z.boolean(),
            justification: z.string()
          }) 
        } 
      }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/gap/evaluate-evidence",
  summary: "Evidence Gap Evaluator (Control Auditor)",
  description: "Evaluates a technical evidence artifact against a control requirement (e.g., SOC2, SCF) and determines via AI agent whether the framework is satisfied.",
  request: {
    body: {
      content: {
        "application/json": {
          schema: EvidenceEvaluationInputSchema
        }
      }
    }
  },
  responses: {
    200: {
      description: "Control evaluation result",
      content: { "application/json": { schema: EvidenceEvaluationOutputSchema } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/poam/architect-remediation",
  summary: "Agile Remediation Planner (PoAM Architect)",
  description: "Given a failed GAP assessment, architecturally creates sprint tickets for the engineering team and recommends CLI commands.",
  request: {
    body: {
      content: {
        "application/json": {
          schema: PoamRemediationInputSchema
        }
      }
    }
  },
  responses: {
    200: {
      description: "Agile remediation outputs",
      content: { "application/json": { schema: PoamRemediationOutputSchema } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/privacy/scan-vendor-contract",
  summary: "B2B Legal Analyzer (Vendor Risk Scanner)",
  description: "Transforms raw contract text into executive intelligence about sub-processors and LGPD/GDPR privacy compliance.",
  request: {
    body: {
      content: {
        "application/json": {
          schema: VendorScannerInputSchema
        }
      }
    }
  },
  responses: {
    200: {
      description: "Vendor risks and compliance gaps",
      content: { "application/json": { schema: VendorScannerOutputSchema } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/soc/triage-incident",
  summary: "SOC L3 Bot (Incident Triager)",
  description: "Processes raw logs from security tools and instantly determines whether a detection is a false positive or a real incident, linking to LGPD breach notification obligations.",
  request: {
    body: {
      content: {
        "application/json": {
          schema: IncidentTriagerInputSchema
        }
      }
    }
  },
  responses: {
    200: {
      description: "SOC diagnosis and containment actions",
      content: { "application/json": { schema: IncidentTriagerOutputSchema } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/executive/translate-risk",
  summary: "CISO/DPO Board Translator",
  description: "Translates complex cybersecurity vulnerabilities into a C-Level/Board-friendly format with financial impact, regulatory consequences, and recommended executive decisions.",
  request: {
    body: {
      content: {
        "application/json": {
          schema: BoardTranslatorInputSchema
        }
      }
    }
  },
  responses: {
    200: {
      description: "Executive summary for the Board of Directors and C-Suite.",
      content: { "application/json": { schema: BoardTranslatorOutputSchema } }
    }
  }
});

// ==========================================
// Agent Runtime Routes
// ==========================================

registry.registerPath({
  method: "get",
  path: "/api/v1/agent-runtime/agents",
  summary: "List Available AI Agents",
  description: "Returns the catalog of all registered functional agents and their allowed tools.",
  responses: {
    200: {
      description: "Agent catalog",
      content: { "application/json": { schema: z.object({ agents: z.array(z.unknown()), tools: z.array(z.unknown()) }) } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/agent-runs",
  summary: "Start Agent Run",
  description: "Initiates an AI agent run for a specific assessment. The run is scoped to the assessment's tenant and generates structured output via LLM.",
  request: {
    params: z.object({ assessmentId: z.string() }),
    body: {
      content: { "application/json": { schema: StartAgentRunInput } }
    }
  },
  responses: {
    201: {
      description: "Agent run created",
      content: { "application/json": { schema: AgentRunSchema } }
    },
    404: {
      description: "Assessment not found",
      content: { "application/json": { schema: ApiErrorSchema } }
    }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}/agent-runs",
  summary: "List Agent Runs for Assessment",
  description: "Returns all AI agent runs for a specific assessment.",
  request: {
    params: z.object({ assessmentId: z.string() })
  },
  responses: {
    200: {
      description: "List of agent runs",
      content: { "application/json": { schema: z.object({ data: z.array(AgentRunSchema) }) } }
    }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/agent-runs/{agentRunId}",
  summary: "Get Agent Run Details",
  description: "Returns the full details, status, and output of a specific agent run.",
  request: {
    params: z.object({ agentRunId: z.string() })
  },
  responses: {
    200: {
      description: "Agent run details",
      content: { "application/json": { schema: AgentRunSchema } }
    },
    404: {
      description: "Agent run not found",
      content: { "application/json": { schema: ApiErrorSchema } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/agent-runs/{agentRunId}/complete",
  summary: "Complete Agent Run",
  description: "Marks an agent run as completed with structured output and optional usage tracking for cost observability.",
  request: {
    params: z.object({ agentRunId: z.string() }),
    body: {
      content: { "application/json": { schema: z.object({ output: z.record(z.string(), z.unknown()), usage: z.object({ prompt_tokens: z.number(), completion_tokens: z.number(), embedding_tokens: z.number().optional(), model_provider: z.string(), estimated_cost: z.number().optional(), currency: z.string().optional() }).optional() }) } }
    }
  },
  responses: {
    200: {
      description: "Agent run completed",
      content: { "application/json": { schema: AgentRunSchema } }
    }
  }
});

// ==========================================
// Assessment CRUD Routes
// ==========================================

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments",
  summary: "List Assessments",
  description: "Returns all assessments for the authenticated tenant. Supports pagination.",
  responses: {
    200: {
      description: "Assessment list",
      content: { "application/json": { schema: z.object({ data: z.array(AssessmentSchema) }) } }
    }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments",
  summary: "Create Assessment",
  description: "Creates a new compliance assessment in 'draft' state.",
  request: {
    body: {
      content: { "application/json": { schema: CreateAssessmentInput } }
    }
  },
  responses: {
    201: {
      description: "Assessment created",
      content: { "application/json": { schema: AssessmentSchema } }
    }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}",
  summary: "Get Assessment",
  description: "Returns full details of a specific assessment including lifecycle state.",
  request: {
    params: z.object({ assessmentId: z.string() })
  },
  responses: {
    200: {
      description: "Assessment details",
      content: { "application/json": { schema: AssessmentSchema } }
    },
    404: {
      description: "Assessment not found",
      content: { "application/json": { schema: ApiErrorSchema } }
    }
  }
});

registry.registerPath({
  method: "delete",
  path: "/api/v1/assessments/{assessmentId}",
  summary: "Delete Assessment",
  description: "Permanently deletes an assessment and all associated artifacts.",
  request: {
    params: z.object({ assessmentId: z.string() })
  },
  responses: {
    204: { description: "Assessment deleted" },
    404: {
      description: "Assessment not found",
      content: { "application/json": { schema: ApiErrorSchema } }
    }
  }
});

// ==========================================
// Health Route
// ==========================================

registry.registerPath({
  method: "get",
  path: "/api/v1/health",
  summary: "Health Check",
  description: "Returns system health status, version, uptime, and operational counters (request count, error rate, average latency).",
  responses: {
    200: {
      description: "System health report",
      content: { "application/json": { schema: HealthResponseSchema } }
    }
  }
});

// ==========================================
// SCF (Secure Controls Framework) Routes
// ==========================================

registry.registerPath({
  method: "get",
  path: "/api/v1/scf/versions",
  summary: "List SCF Versions",
  description: "Returns all available Secure Controls Framework versions (e.g., 2026.1.1).",
  responses: {
    200: { description: "SCF version catalog", content: { "application/json": { schema: z.object({ data: z.array(z.object({ version_id: z.string(), name: z.string(), domain_count: z.number(), control_count: z.number() })) }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/scf/versions/{versionId}/domains",
  summary: "List SCF Domains",
  description: "Returns all domains for a specific SCF version.",
  request: { params: z.object({ versionId: z.string() }) },
  responses: {
    200: { description: "Domain list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ domain_id: z.string(), abbreviation: z.string(), name: z.string(), control_count: z.number() })) }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/scf/versions/{versionId}/controls",
  summary: "List SCF Controls",
  description: "Returns controls for a version, with optional domain filter.",
  request: { params: z.object({ versionId: z.string() }) },
  responses: {
    200: { description: "Control list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ control_id: z.string(), identifier: z.string(), name: z.string(), domain_id: z.string() })), pagination: PaginatedMeta }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/scf/controls/{controlId}",
  summary: "Get SCF Control Details",
  description: "Returns full control details including description, methods, and framework mappings.",
  request: { params: z.object({ controlId: z.string() }) },
  responses: {
    200: { description: "Control details", content: { "application/json": { schema: z.object({ control_id: z.string(), identifier: z.string(), name: z.string(), description: z.string(), methods: z.array(z.string()), frameworks: z.array(z.string()) }) } } },
    404: { description: "Control not found", content: { "application/json": { schema: ApiErrorSchema } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/scf/controls/{controlId}/mappings",
  summary: "Get Control Framework Mappings",
  description: "Returns all framework mappings (ISO27001, NIST, SOC2, etc.) for a specific SCF control.",
  request: { params: z.object({ controlId: z.string() }) },
  responses: {
    200: { description: "Framework mappings", content: { "application/json": { schema: z.object({ control_id: z.string(), mappings: z.array(z.object({ framework: z.string(), reference: z.string() })) }) } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/intelligence/blast-radius",
  summary: "Get SCF Blast Radius",
  description: "Returns the impact topology (linked regulations, risks, categories) of a given control.",
  request: { body: { content: { "application/json": { schema: BlastRadiusRequestSchema } } } },
  responses: {
    200: { description: "Blast Radius topology", content: { "application/json": { schema: BlastRadiusOutputSchema } } }
  }
});

// ==========================================
// Intelligence Engine Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/intelligence/gap-analysis",
  summary: "Run Intelligence Gap Analysis",
  description: "Calculate missing controls against a target framework securely.",
  request: { body: { content: { "application/json": { schema: GapAnalysisRequestSchema } } } },
  responses: {
    200: { description: "Gap analysis results", content: { "application/json": { schema: GapAnalysisOutputSchema } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/intelligence/compliance-score",
  summary: "Calculate Compliance Score",
  description: "Get real-time compliance score for a regulation based on implemented controls.",
  request: { body: { content: { "application/json": { schema: ComplianceScoreRequestSchema } } } },
  responses: {
    200: { description: "Compliance Score outputs", content: { "application/json": { schema: ComplianceScoreOutputSchema } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/intelligence/dpia-score",
  summary: "Get DPIA Trigger Score",
  description: "Calculate DPIA severity triggering based on volume, categories, and controls.",
  request: { body: { content: { "application/json": { schema: DpiaScoreRequestSchema } } } },
  responses: {
    200: { description: "DPIA score results", content: { "application/json": { schema: DpiaScoreOutputSchema } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/intelligence/cross-coverage",
  summary: "Calculate Cross-framework Coverage",
  description: "See how implementing one framework covers another.",
  request: { body: { content: { "application/json": { schema: CrossCoverageRequestSchema } } } },
  responses: {
    200: { description: "Cross Coverage results", content: { "application/json": { schema: CrossCoverageOutputSchema } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/intelligence/roi-path",
  summary: "Calculate Optimal ROI Path",
  description: "Determines the Shortest Path to compliance by finding the most impactful missing controls.",
  request: { body: { content: { "application/json": { schema: RoiPathRequestSchema } } } },
  responses: {
    200: { description: "ROI Path results", content: { "application/json": { schema: RoiPathOutputSchema } } }
  }
});

// ==========================================
// Documents & Knowledge Base Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/documents",
  summary: "Upload Document",
  description: "Uploads a document to an assessment for evidence analysis. Triggers async ingestion and chunking for the KB.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    201: { description: "Document uploaded", content: { "application/json": { schema: z.object({ document_id: z.string(), filename: z.string(), status: z.string() }) } } },
    404: { description: "Assessment not found", content: { "application/json": { schema: ApiErrorSchema } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}/documents",
  summary: "List Assessment Documents",
  description: "Returns all documents uploaded to an assessment.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    200: { description: "Document list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ document_id: z.string(), filename: z.string(), mime_type: z.string(), file_size: z.number(), uploaded_at: z.string() })) }) } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/kb/search",
  summary: "Semantic KB Search",
  description: "Performs vector similarity search across the knowledge base. Returns relevant document chunks for a natural language query.",
  request: {
    body: { content: { "application/json": { schema: z.object({ query: z.string().openapi({ example: "encryption at rest policy" }), limit: z.number().optional().openapi({ example: 10 }) }) } } }
  },
  responses: {
    200: { description: "Search results", content: { "application/json": { schema: z.object({ data: z.array(z.object({ chunk_id: z.string(), content: z.string(), score: z.number(), document_id: z.string() })) }) } } }
  }
});

// ==========================================
// Statement of Applicability (SoA) Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/soa/generate",
  summary: "Generate Statement of Applicability",
  description: "Creates a new SoA version by analyzing the assessment's SCF controls against KB evidence.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    201: { description: "SoA version created", content: { "application/json": { schema: z.object({ soa_version_id: z.string(), assessment_id: z.string(), status: z.string(), control_count: z.number() }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}/soa",
  summary: "List SoA Versions",
  description: "Returns all Statement of Applicability versions for an assessment.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    200: { description: "SoA version list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ soa_version_id: z.string(), status: z.string(), created_at: z.string() })) }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/soa/{soaVersionId}/entries",
  summary: "List SoA Entries",
  description: "Returns all control applicability entries for a SoA version.",
  request: { params: z.object({ soaVersionId: z.string() }) },
  responses: {
    200: { description: "SoA entries", content: { "application/json": { schema: z.object({ data: z.array(z.object({ control_id: z.string(), is_applicable: z.boolean(), justification: z.string(), implementation_status: z.string() })), pagination: PaginatedMeta }) } } }
  }
});

// ==========================================
// Gap Analysis Workflow Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/evidence-analysis/run",
  summary: "Run Evidence Analysis",
  description: "Triggers AI evidence analysis against the SoA to identify compliance gaps.",
  request: {
    params: z.object({ assessmentId: z.string() }),
    body: { content: { "application/json": { schema: z.object({ soa_version_id: z.string() }) } } }
  },
  responses: {
    201: { description: "Evidence analysis result", content: { "application/json": { schema: z.object({ evidence_findings_count: z.number(), status: z.string() }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}/evidence-findings",
  summary: "List Evidence Findings",
  description: "Returns evidence findings from the AI analysis for an assessment.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    200: { description: "Evidence findings", content: { "application/json": { schema: z.object({ data: z.array(z.object({ evidence_finding_id: z.string(), control_id: z.string(), status: z.string(), confidence_score: z.number() })), pagination: PaginatedMeta }) } } }
  }
});

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/gap-analysis/draft",
  summary: "Create Gap Analysis Draft",
  description: "Creates a new gap analysis draft from evidence findings.",
  request: {
    params: z.object({ assessmentId: z.string() }),
    body: { content: { "application/json": { schema: z.object({ soa_version_id: z.string() }) } } }
  },
  responses: {
    201: { description: "Gap analysis draft created", content: { "application/json": { schema: z.object({ gap_analysis_version_id: z.string(), status: z.string() }) } } }
  }
});

// ==========================================
// POA&M Workflow Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/poam/generate",
  summary: "Generate POA&M",
  description: "Generates a Plan of Action & Milestones from approved gap analysis findings.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    201: { description: "POA&M version created", content: { "application/json": { schema: z.object({ poam_version_id: z.string(), assessment_id: z.string(), item_count: z.number() }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}/poam",
  summary: "List POA&M Versions",
  description: "Returns all POA&M versions for an assessment.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    200: { description: "POA&M version list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ poam_version_id: z.string(), status: z.string(), item_count: z.number(), created_at: z.string() })) }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/poam/{poamVersionId}/items",
  summary: "List POA&M Items",
  description: "Returns all remediation items for a POA&M version with priority, effort, and sprint actions.",
  request: { params: z.object({ poamVersionId: z.string() }) },
  responses: {
    200: { description: "POA&M items", content: { "application/json": { schema: z.object({ data: z.array(z.object({ poam_item_id: z.string(), control_id: z.string(), priority: z.string(), estimated_effort: z.string(), status: z.string() })), pagination: PaginatedMeta }) } } }
  }
});

// ==========================================
// Reporting Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/assessments/{assessmentId}/reports/generate",
  summary: "Generate Compliance Report",
  description: "Generates a compliance report (PDF/JSON) from assessment data including SoA, gap analysis, and POA&M.",
  request: {
    params: z.object({ assessmentId: z.string() }),
    body: { content: { "application/json": { schema: z.object({ format: z.enum(["pdf", "json", "xlsx"]).optional(), template: z.string().optional() }) } } }
  },
  responses: {
    202: { description: "Report generation started", content: { "application/json": { schema: z.object({ report_id: z.string(), status: z.string() }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/assessments/{assessmentId}/reports",
  summary: "List Assessment Reports",
  description: "Returns all generated reports for an assessment.",
  request: { params: z.object({ assessmentId: z.string() }) },
  responses: {
    200: { description: "Report list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ report_id: z.string(), format: z.string(), status: z.string(), created_at: z.string() })) }) } } }
  }
});

// ==========================================
// API Keys & Auth Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/api-keys",
  summary: "Create API Key",
  description: "Creates a new M2M API key with scoped permissions. The raw key is returned only once.",
  request: {
    body: { content: { "application/json": { schema: z.object({ name: z.string(), scopes: z.array(z.string()), expires_in_days: z.number().optional() }) } } }
  },
  responses: {
    201: { description: "API key created", content: { "application/json": { schema: z.object({ id: z.string(), name: z.string(), key: z.string().openapi({ description: "Raw key — shown only once" }), masked_key: z.string(), scopes: z.array(z.string()), expires_at: z.string().nullable() }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/api-keys",
  summary: "List API Keys",
  description: "Returns all API keys for the authenticated tenant (masked, no raw keys).",
  responses: {
    200: { description: "API key list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ id: z.string(), name: z.string(), masked_key: z.string(), scopes: z.array(z.string()), last_used_at: z.string().nullable() })) }) } } }
  }
});

// ==========================================
// Organizations Routes
// ==========================================

registry.registerPath({
  method: "get",
  path: "/api/v1/organizations",
  summary: "List Organizations",
  description: "Returns all organizations for the authenticated tenant.",
  responses: {
    200: { description: "Organization list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ organization_id: z.string(), name: z.string(), slug: z.string(), status: z.string() })) }) } } }
  }
});

// ==========================================
// Webhook Routes
// ==========================================

registry.registerPath({
  method: "post",
  path: "/api/v1/webhooks",
  summary: "Register Webhook",
  description: "Registers a webhook endpoint to receive real-time notifications for assessment lifecycle events.",
  request: {
    body: { content: { "application/json": { schema: z.object({ url: z.string().url(), events: z.array(z.string().openapi({ example: "assessment.state_changed" })), secret: z.string().optional() }) } } }
  },
  responses: {
    201: { description: "Webhook registered", content: { "application/json": { schema: z.object({ webhook_id: z.string(), url: z.string(), events: z.array(z.string()), status: z.string() }) } } }
  }
});

registry.registerPath({
  method: "get",
  path: "/api/v1/webhooks",
  summary: "List Webhooks",
  description: "Returns all registered webhooks for the authenticated tenant.",
  responses: {
    200: { description: "Webhook list", content: { "application/json": { schema: z.object({ data: z.array(z.object({ webhook_id: z.string(), url: z.string(), events: z.array(z.string()), status: z.string() })) }) } } }
  }
});

export const generateOpenAPI = () => {
  const generator = new OpenApiGeneratorV3(registry.definitions);
  return generator.generateDocument({
    openapi: "3.0.0",
    info: {
      title: "Standard GRC Platform — API Reference",
      version: "1.0.0",
      description: "API-first agentic GRC platform for compliance assessments powered by the Secure Controls Framework (SCF). Features 7 specialized AI agents, assessment lifecycle management, document ingestion, knowledge base search, and multi-tenant authorization."
    },
    servers: [
      { url: "/", description: "Current environment" },
      { url: "https://standard-api-gateway-production.ness.workers.dev", description: "Production" }
    ],
    security: [{ BearerApiKey: [] }]
  });
};
